### PR TITLE
Instant checkout

### PR DESCRIPTION
**Pull request by nickendle**

### CODE REVIEW

**Comment by outerim** [comment]
I sorta hated the ENV var to be honest 😂. It was kinda a quick and dirty way to make it work and I didn’t have a better idea for how to allow that to be configured at the time. In retrospect I think the `.dugway.json` settings probably make a lot of sense. I don’t recall if that was something I explored and failed to get it working or if it just didn’t occur to me at the time... I’ll revisit this.

**Comment by hwinn4** [comment]
@outerim Cool, sounds good!

**Comment by nickendle** [comment]
@outerim is this still something you wanted to revisit?

**Comment by outerim** [comment]
@nickendle sorta?! :) but at this point I feel like it's probably fine to merge if you're ok with it.

**Pull request closed without merging**
